import { useState } from 'react';
import type { Company, Payload } from './model';
import type { PortfolioSnapshot } from './TodayWorkspace';

export const companyTabs = [['overview','研究判断'],['evidence','证据与资料'],['metrics','财务与估值'],['relations','产业与关系'],['activity','模拟记录']];
function sourceUrl(value?:string) { return value && /^https?:\/\//i.test(value) ? value : undefined; }
export function ResearchCenter({ data, companyId, detail, onSelect, onDetail, onEdit, onPortfolio, paper, paperError }: {
  data:Payload; companyId:number; detail:string; onSelect:(id:number)=>void; onDetail:(tab:string)=>void;
  onEdit:(company:Company)=>void; onPortfolio:()=>void; paper:PortfolioSnapshot|null; paperError:string;
}) {
  const [query,setQuery]=useState(''); const [market,setMarket]=useState('全部');
  const companies=data.companies.filter(c=>(market==='全部'||c.market===market)&&[c.name,c.ticker,c.sector,c.chain].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
  const company=data.companies.find(c=>c.id===companyId) ?? (!companyId ? data.companies[0] : undefined);
  const facts=(data.facts??[]).filter(f=>f.companyId===company?.id);
  const documents=(data.documents??[]).filter(d=>d.companyId===company?.id);
  const metrics=(data.factorMetrics??[]).filter(m=>m.companyId===company?.id);
  const relations=data.relations.filter(r=>r.sourceId===company?.id||r.targetId===company?.id);
  const orders=paper?.orders.filter(o=>o.companyId===company?.id)??[];
  return <div className="ma-research-grid"><aside className="ma-company-list ma-panel"><label className="ma-field">查找公司<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="名称、代码、行业" /></label><label className="ma-field">市场<select value={market} onChange={e=>setMarket(e.target.value)}>{['全部',...new Set(data.companies.map(c=>c.market))].map(m=><option key={m}>{m}</option>)}</select></label><p className="ma-muted">{companies.length} / {data.companies.length} 家公司</p><div className="ma-company-scroll">{companies.map(c=><button key={c.id} aria-pressed={company?.id===c.id} className={`ma-company-item ${company?.id===c.id?'is-active':''}`} onClick={()=>onSelect(c.id)}><b>{c.name}</b><small>{c.ticker} · {c.market}</small><span>{c.sector}</span></button>)}{!companies.length&&<p className="ma-empty">没有匹配公司。请调整筛选。</p>}</div></aside>
    <section className="ma-panel ma-company-detail">{!company ? <p className="ma-empty">{companyId ? '该公司不存在，请从左侧重新选择。' : '暂无公司，请先新建卡片。'}</p> : <><div className="ma-section-head"><div><p className="ma-kicker">COMPANY RESEARCH</p><h2>{company.name}</h2><p className="ma-muted">{company.ticker} · {company.market} · {company.sector}</p></div><button onClick={()=>onEdit(company)}>编辑卡片</button></div><div className="ma-tabs" aria-label="公司研究内容">{companyTabs.map(([id,label])=><button key={id} aria-pressed={detail===id} onClick={()=>onDetail(id)}>{label}</button>)}</div>
      {detail==='overview'&&<div className="ma-stack"><div className="ma-note">研究判断与交易时点分开：这里记录公司逻辑，模拟组合保留现有长期吸引力与短期入场条件的双列排名。</div><section><h3>主营业务与核心判断</h3><p>{company.summary||'尚未填写'}</p></section><div className="ma-two"><section className="ma-inset"><h3>核心护城河</h3><p>{company.moat||'尚未填写，不能默认存在护城河。'}</p></section><section className="ma-inset"><h3>潜在催化剂</h3><p>{company.catalyst||'尚未填写'}</p></section></div><section className="ma-inset ma-risk"><h3>主要风险与反证方向</h3><p>{company.risk||'尚未填写；请补充可能推翻判断的条件。'}</p></section><div className="ma-actions"><button onClick={()=>onDetail('evidence')}>核对 {documents.length} 份资料 / {facts.length} 条事实 →</button><button onClick={onPortfolio}>查看入场条件与模拟记录 →</button></div></div>}
      {detail==='evidence'&&<div className="ma-stack"><p className="ma-note">资料 → 可追溯事实 → 支持或反驳驱动假设。置信度是已有研究记录，不代表已独立核验，也不直接代表投资吸引力。</p><section><h3>原始资料 · {documents.length}</h3>{documents.map(d=><article key={d.id} className="ma-record"><b>{d.title}</b><p className="ma-muted">{d.documentType} · {d.reportingPeriod||'报告期待补'} · 公开日期 {d.publicationDate||'待补'} · {d.sourceTier}</p>{sourceUrl(d.url)?<a href={sourceUrl(d.url)} target="_blank" rel="noreferrer">查看原始来源 ↗</a>:<span>来源链接待补</span>}</article>)}{!documents.length&&<p className="ma-empty">暂无原始资料，不使用示例内容填补。</p>}</section><section><h3>事实、传导逻辑与反证 · {facts.length}</h3>{facts.map(f=>{const doc=documents.find(d=>d.id===f.documentId); const links=(data.driverFactLinks??[]).filter(l=>l.factId===f.id);return <article className="ma-record" key={f.id}><h4>{f.label}：{f.valueText} {f.unit}</h4><p>{f.evidenceSummary||'事实解释待补'}</p><p className="ma-muted">{f.reportingPeriod} · 位置 {f.location||'待补'} · 记录置信度 {f.confidence}/5 · 核验记录日期 {f.verifiedAt||'待补'}</p><small>来源：{doc?.title||'原始文件尚未关联'}</small>{links.map(l=><div key={l.id} className="ma-note"><b>{l.stance} · {data.drivers?.find(d=>d.id===l.driverId)?.name||'驱动待关联'}</b><p>{l.rationale||'传导逻辑待补'}</p></div>)}{!links.length&&<p className="ma-muted">尚未连接驱动假设，不能自动推导利好或利空。</p>}</article>})}{!facts.length&&<p className="ma-empty">尚未提取事实。</p>}</section></div>}
      {detail==='metrics'&&<><p className="ma-note">保留指标报告期、公开日期和观察日期；不同口径不可直接混用。此处不重新计算评分。</p><div className="ma-table-wrap"><table><thead><tr><th>指标</th><th>数值</th><th>报告期</th><th>公开日期</th><th>观察日期</th><th>来源文件</th></tr></thead><tbody>{metrics.map(m=><tr key={m.id}><td>{m.metric}</td><td>{Number.isFinite(m.value)?m.value.toLocaleString('zh-CN',{maximumFractionDigits:4}):'缺失'} {m.unit}</td><td>{m.reportingPeriod||'—'}</td><td>{m.publishedAt||'—'}</td><td>{m.observedAt||'—'}</td><td>{documents.find(d=>d.id===m.sourceDocumentId)?.title||'未关联'}</td></tr>)}</tbody></table></div>{!metrics.length&&<p className="ma-empty">尚无财务或估值指标；缺失数据不按零值处理。</p>}</>}
      {detail==='relations'&&<div className="ma-stack"><section><h3>产业归属与宏观暴露</h3><p>{company.chain} · {company.position}</p><div className="ma-tags">{data.memberships?.filter(m=>m.companyId===company.id).map(m=><span key={m.id}>{m.chainName} · {m.stage} · {m.role}</span>)}{data.tags?.filter(t=>t.companyId===company.id).map(t=><span key={'t'+t.id}>{t.tagType}：{t.tagName}</span>)}{data.exposures?.filter(x=>x.companyId===company.id).map(x=><span key={'e'+x.id}>{x.factor} · {x.direction} · {x.sensitivity}</span>)}</div></section><section><h3>直接关联 · {relations.length}</h3>{relations.map(r=>{const source=data.companies.find(c=>c.id===r.sourceId),target=data.companies.find(c=>c.id===r.targetId);const other=company.id===r.sourceId?target:source;return <article className="ma-record" key={r.id}><b>{source?.name||'未关联'} → {r.type} → {target?.name||'未关联'}</b><p>{r.note||'关系证据待补'}</p>{other&&<button onClick={()=>onSelect(other.id)}>查看 {other.name} →</button>}</article>})}{!relations.length&&<p className="ma-empty">暂无已录入关系，不代表没有上下游联系。</p>}</section></div>}
      {detail==='activity'&&<><p className="ma-note">仅展示本地模拟订单；切换公司或页面不会下单。</p>{!paper&&<p className="ma-empty">{paperError||'正在读取模拟记录…'}</p>}{paper&&!orders.length&&<p className="ma-empty">该公司尚无模拟订单。</p>}{orders.map(o=><article key={o.id} className="ma-record"><b>{o.side} · {o.quantity.toLocaleString()} 股 · {o.status}</b><p>{o.rationale||'未记录理由'}</p><small>{o.signalDate||'日期未记录'}</small></article>)}<button onClick={onPortfolio}>进入模拟组合 →</button></>}
    </>}</section></div>;
}
